version: 2
jobs:
  run_tests:
    docker:
      - image: python:3.9

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca_tracker
            python -m venv /tmp/venv/openfisca_tracker
            echo "source /tmp/venv/openfisca_tracker/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            make install

      - save_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/openfisca_tracker

      - run:
          name: Run Core tests
          command: env PYTEST_ADDOPTS="--exitfirst" make test

workflows:
  version: 2
  build:
    jobs:
      - run_tests
